version: '3.3'
services:

  frontend:
    image: nucluster/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  
  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: nucluster/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/backend_static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.24.0-alpine3.17-slim
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/backend_static/
      - media_volume:/var/html/media/
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume:
  db_volume:
